### ISSUE TITLE
重装漏洞

### ISSUE THREAD

**Issue by 360CodeSafe** [gongfuxiang/shopxo#1]
您好：
我是360代码卫士的工作人员，在我们的开源代码审计过程中，发现shopxo存在系统重装漏洞，详细信息如下：
在shopxo\application\install\controller\Index.php文件中，Add方法中没有校验锁文件，导致攻击者可以重装数据库。
![default](https://user-images.githubusercontent.com/39950310/50678981-40a2bd00-103c-11e9-9d6f-61946a1d406f.png)
构造如下post请求
![default](https://user-images.githubusercontent.com/39950310/50679281-d12dcd00-103d-11e9-9481-a486c38158c2.png)

可以发现本地数据库中新建了一个shopxo2的数据库，实际场景中攻击者可以在自己额公网服务器中的数据库开启远程连接，连上自己的数据库
![default](https://user-images.githubusercontent.com/39950310/50679224-962b9980-103d-11e9-8618-43db0ebd682f.png)

最关键的地方是数据库配置文件也修改了
![default](https://user-images.githubusercontent.com/39950310/50679309-e9055100-103d-11e9-9fc9-8a3b785de459.png)
这个地方可以通过写入php代码来getshell，由于是在github上，详细信息就不具体说了，如果您对后面getshell的方法流程感兴趣，很乐意通过邮件告诉您

**Comment by gongfuxiang** [comment]
已修复

**Comment by attritionorg** [comment]
@gongfuxiang Can you link to the fixing commit please?

**Comment by gongfuxiang** [comment]
> @gongfuxiang你能链接到修复提交吗？

https://github.com/gongfuxiang/shopxo/blob/v1.5.0/application/install/controller/Index.php
