### ISSUE TITLE
涉及到数据库事务的代码, 有点乱~~~

### ISSUE THREAD

**Issue by yangqinjiang** [gongfuxiang/shopxo#18]
涉及到数据库事务的代码, 有点乱~~~

看这里`application/service/OrderService.php:399`
`Db::startTrans();

        // 消息通知
        $detail = '订单支付成功，金额'.PriceBeautify($params['order']['total_price']).'元';
        MessageService::MessageAdd($params['order']['user_id'], '订单支付', $detail, 1, $params['order']['id']);

        // 更新订单状态
        $upd_data = array(
            'status'        => 2,
            'pay_status'    => 1,
            'pay_price'     => $pay_price,
            'payment_id'    => $params['payment']['id'],
            'pay_time'      => time(),
            'upd_time'      => time(),
        );
        if(Db::name('Order')->where(['id'=>$params['order']['id']])->update($upd_data))
        {
            // 添加状态日志
            if(self::OrderHistoryAdd($params['order']['id'], 2, $params['order']['status'], '支付', 0, '系统'))
            {
                // 库存扣除
                $ret = BuyService::OrderInventoryDeduct(['order_id'=>$params['order']['id'], 'order_data'=>$upd_data]);
                if($ret['code'] != 0)
                {
                    // 事务回滚
                    Db::rollback();
                    return DataReturn($ret['msg'], -10);
                }

                // 提交事务
                Db::commit();
                return DataReturn('支付成功', 0);
            }
        }

        // 事务回滚
        Db::rollback();`

**Comment by gongfuxiang** [comment]
没看出乱呀

**Comment by yangqinjiang** [comment]
> 没看出乱呀

看看官方提供的示例
`https://www.kancloud.cn/manual/thinkphp5_1/354035`

**Comment by gongfuxiang** [comment]
不能照搬的，官网的demo只是保证sql运行成功，并不能保证业务处理成功。
在实际业务中，sql成功了不一定就是成功了，很多逻辑需要校验，校验失败还得回滚事务。

**Comment by yangqinjiang** [comment]
> 不能照搬的，官网的demo只是保证sql运行成功，并不能保证业务处理成功。
> 在实际业务中，sql成功了不一定就是成功了，很多逻辑需要校验，校验失败还得回滚事务。

也有可能是你的业务逻辑不够好
