### ISSUE TITLE
后台任意文件删除漏洞

### ISSUE THREAD

**Issue by 360CodeSafe** [gongfuxiang/shopxo#2]
后台删除文件处由于没有对文件名做校验导致可以通过../进行回溯来删除任意文件夹，删除install文件(锁文件所在的文件夹)时，可以重装系统
在Appminialipaylist.php文件中，params是受控制的：
![default](https://user-images.githubusercontent.com/39950310/50682006-6766f080-1048-11e9-9440-cb5f72912efb.png)
进入delete方法中，当不是zip结尾时会认为是文件夹
![default](https://user-images.githubusercontent.com/39950310/50682083-a432e780-1048-11e9-9ff2-6802ac2172df.png)
跟进FileUtil.php文件UnlinkDir方法中
![default](https://user-images.githubusercontent.com/39950310/50682117-c75d9700-1048-11e9-9ff4-43a6cd60bd92.png)
方法中只对是不是文件夹做了校验，最后进入了rmdir方法中

点击删除
![default](https://user-images.githubusercontent.com/39950310/50682479-ead51180-1049-11e9-86a3-5b713720fc15.png)
抓包修改
![default](https://user-images.githubusercontent.com/39950310/50682525-1821bf80-104a-11e9-87da-0cffcf19d39a.png)

成功删除
![default](https://user-images.githubusercontent.com/39950310/50682494-f9232d80-1049-11e9-8360-25830d81c620.png)

**Comment by gongfuxiang** [comment]
已修复

**Comment by attritionorg** [comment]
@gongfuxiang can you link to the fixing commit please?

**Comment by OrenSavichWS** [comment]
Hi, can you link to the fixing commit please?
