### ISSUE TITLE
版本通杀无条件登陆任意用户

### ISSUE THREAD

**Issue by qhxb** [gongfuxiang/shopxo#23]
APPLICATION、$params['user_id']可以被用户控制，存在变量覆盖问题。
![image](https://user-images.githubusercontent.com/22363218/60959703-43f46980-a33b-11e9-8aea-9c7a5f597472.png)
利用修改头像接口
1、添加参数application=app跟参数user_id，导致$params['user_id']用户id变成用户指定id
![image](https://user-images.githubusercontent.com/22363218/60960128-ffb59900-a33b-11e9-8db1-5df7ef8aeba9.png)
2、进入UserLoginRecord方法，这里好像没啥问题
![image](https://user-images.githubusercontent.com/22363218/60959972-bbc29400-a33b-11e9-8c0e-16ace8a4f8f1.png)
3、进入UserAvatarUpload方法，这里完成图片上传后又调用了UserLoginRecord方法
![image](https://user-images.githubusercontent.com/22363218/60960562-dfd2a500-a33c-11e9-8cf0-81b12b3da78d.png)
4、再进入UserLoginRecord方法。因为这次调用没有指定$is_app，默认为false
![image](https://user-images.githubusercontent.com/22363218/60960766-448dff80-a33d-11e9-97d9-5db9a7c0b8f5.png)
这就导致了最终结果变成当前session存储的用户变成用户指定的任意用户id，并且这个id是一个可以猜测的简单数字
5、最终效果
![image](https://user-images.githubusercontent.com/22363218/60961095-f88f8a80-a33d-11e9-83d9-2003f63ccc1a.png)

**Comment by gongfuxiang** [comment]
非常感谢你的反馈，1.6已经修复了该问题，请在1.6上验证一下

**Comment by gongfuxiang** [comment]
> APPLICATION，$ params ['user_id']可以被用户控制，存在变量覆盖问题。 利用修改头像接口 1，添加参数application = app跟参数user_id，导致$ params ['user_id']用户id变成用户指定id 2 ，进入UserLoginRecord方法，这里好像没啥问题 3，进入UserAvatarUpload方法，这里完成图片上传后又调用了UserLoginRecord方法 4，再进入UserLoginRecord方法。因为这次调用没有指定$ IS_APP，默认为假 这就导致了最终结果变成当前会话存储的用户变成用户指定的任意用户ID，并且这个ID是一个可以猜测的简单数字 5，最终效果
> ![图片](https://user-images.githubusercontent.com/22363218/60959703-43f46980-a33b-11e9-8aea-9c7a5f597472.png)
> 
> 
> ![图片](https://user-images.githubusercontent.com/22363218/60960128-ffb59900-a33b-11e9-8db1-5df7ef8aeba9.png)
> 
> ![图片](https://user-images.githubusercontent.com/22363218/60959972-bbc29400-a33b-11e9-8c0e-16ace8a4f8f1.png)
> 
> ![图片](https://user-images.githubusercontent.com/22363218/60960562-dfd2a500-a33c-11e9-8cf0-81b12b3da78d.png)
> 
> ![图片](https://user-images.githubusercontent.com/22363218/60960766-448dff80-a33d-11e9-97d9-5db9a7c0b8f5.png)
> 
> 
> ![图片](https://user-images.githubusercontent.com/22363218/60961095-f88f8a80-a33d-11e9-83d9-2003f63ccc1a.png)

非常感谢你的反馈，1.6已经修复了该问题，请在1.6上验证一下

**Comment by qhxb** [comment]
![image](https://user-images.githubusercontent.com/22363218/60964638-663fb480-a346-11e9-9fce-667497658ff9.png)
1.6一直部署成功，但是点首页报错

**Comment by gongfuxiang** [comment]
> ![image](https://user-images.githubusercontent.com/22363218/60964638-663fb480-a346-11e9-9fce-667497658ff9.png)
> 1.6部署成功，但是点首页报错

application/tags.php
用1.5这个文件替换一下、开发版本里面有不存在的狗子
https://gitee.com/gongfuxiang/shopxo/blob/master/application/tags.php

**Comment by qhxb** [comment]
v1.6.0修复了，没这个问题了
