### ISSUE TITLE
未定义变量

### ISSUE THREAD

**Issue by bluedragonflyliu** [gongfuxiang/shopxo#42]
application/service/PaymentService.php 153 $payment 三元运算符 :后面是否是空字符串，现在是$payment

**Comment by gongfuxiang** [comment]
非常感谢你的反馈，v1.8.1版本已修复

**Comment by gongfuxiang** [comment]
> application/service/PaymentService.php 153 $payment 三元运算符 :后面是否是空字符串，现在是$payment

非常感谢你的反馈，v1.8.1版本已修复
