### ISSUE TITLE
Index/user/index 的问题

### ISSUE THREAD

**Issue by bluedragonflyliu** [gongfuxiang/shopxo#43]
我看了很久index模块下user控制器下index方法里面有很多钩子，没看到有什么效果，很迷惑。

**Comment by gongfuxiang** [comment]
> 我看了很久index模块下user控制器下index方法里面有很多钩子，没看到有什么效果，很迷惑。

钩子是给插件使用的，预留的钩子，你可以参考一下插件开发教程 [](https://doc.shopxo.net/docs/dev-plugins)

**Comment by bluedragonflyliu** [comment]
谢谢，终于明白为什么页面有很多点点
