### ISSUE TITLE
用户注册图片验证码 后台关闭 但前台还是是显示

### ISSUE THREAD

**Issue by marcelowu** [gongfuxiang/shopxo#50]
![Captura de tela de 2020-12-05 21-45-30](https://user-images.githubusercontent.com/30912144/101268621-fbb1c480-3743-11eb-8e96-2568699593f2.png)
![Captura de tela de 2020-12-05 21-46-18](https://user-images.githubusercontent.com/30912144/101268623-02d8d280-3744-11eb-9bff-fadb9635108f.png)

**Comment by gongfuxiang** [comment]
这个关闭的是图片验证码
