### ISSUE TITLE
适合国外使用吗

### ISSUE THREAD

**Issue by marcelowu** [gongfuxiang/shopxo#52]

**Comment by gongfuxiang** [comment]
你好，适合的，系统有汇率插件，国外支付方式也有很多种。查看应用商店  http://store.shopxo.net

**Comment by marcelowu** [comment]
带有葡萄牙语？
没有 GDPR插件？
 就是用户可以注销账号，然后所有和该用户相关的信息都会清除，项目中如果用Cookie就需要客户知道之类的
